
- hosts: yayoi2
  become: yes
  tasks:
  - name: install required packages
    apt: name={{ item }}
    with_items:
      - libnuma-dev
      - libelf-dev
      - golang
      - go-dep

  - name: set hugepages
    hugepages: nr_pages=1024

  - name: install dpdk
    dpdk_install: build_shared_lib=true jobs=6

  - name: bind device to dpdk driver
    devbind: device=000:01:00.0 driver=igb_uio


- hosts: yayoi2
  vars:
    GOPATH : /home/upa/go2
  environment:
    GOPATH: "{{ GOPATH }}"
  tasks:

#  - name: install openconfigd
#    go_get: package={{ item }}
#    with_items:
#      - github.com/coreswitch/openconfigd/openconfigd
#      - github.com/coreswitch/openconfigd/cli_command
  - name: go get openconfigd
    command: "{{ item }}"
    with_items:
      - go get github.com/coreswitch/openconfigd/openconfigd
      - go get github.com/coreswitch/openconfigd/cli_command

  - name: configure, make, make install cli
    become: yes
    command: "{{ item }}"
    with_items:
      - ./configure
      - make
      - make install
      - cp ../bash_completion.d/cli /etc/bash_completion.d/
    args:
      chdir: "{{ GOPATH }}/src/github.com/coreswitch/openconfigd/cli"

  - name: create vsw src directroy
    file: path={{ GOPATH }}/src/github.com/lagopus state=directory

  - name: download vsw
    git:
      repo: https://github.com/lagopus/vsw.git
      dest: "{{ GOPATH }}/src/github.com/lagopus/vsw"

  - name: install vsw
    command: "{{ item }}"
    with_items:
      - dep ensure
      - go install
    args:
      chdir: "{{ GOPATH }}/src/github.com/lagopus/vsw"

  - name: install lagopus-router
    git:
      repo: https://github.com/lagopus/lagopus-router.git
      dest: "{{ GOPATH }}/src/github.com/lagopus/lagopus-router"
