
# install required software
- hosts: localhost
  become: yes
  tasks:
  - name: install required packages
    apt:
      name: [ "libnuma-dev", "libelf-dev", "golang", "go-dep" ]

  - name: install dpdk
    dpdk_install: build_shared_lib=true jobs=6


# install lagopus-router and related software
- hosts: localhost
  vars:
    GOPATH : /home/upa/go2
  environment:
    GOPATH: "{{ GOPATH }}"
  tasks:

  - name: go get openconfigd
    command: "{{ item }}"
    with_items:
      - go get github.com/coreswitch/openconfigd/openconfigd
      - go get github.com/coreswitch/openconfigd/cli_command

  - name: configure, make, make install cli
    become: yes
    command: "{{ item }}"
    with_items:
      - ./configure
      - make
      - make install
      - cp ../bash_completion.d/cli /etc/bash_completion.d/
    args:
      chdir: "{{ GOPATH }}/src/github.com/coreswitch/openconfigd/cli"

  - name: create vsw src directroy
    file: path={{ GOPATH }}/src/github.com/lagopus state=directory

  - name: download vsw
    git:
      repo: https://github.com/lagopus/vsw.git
      dest: "{{ GOPATH }}/src/github.com/lagopus/vsw"

  - name: install vsw
    command: "{{ item }}"
    with_items:
      - dep ensure
      - go install
    args:
      chdir: "{{ GOPATH }}/src/github.com/lagopus/vsw"

  - name: install lagopus-router
    git:
      repo: https://github.com/lagopus/lagopus-router.git
      dest: "{{ GOPATH }}/src/github.com/lagopus/lagopus-router"


# setup, spawn, and configure vsw
- hosts: localhost
  vars:
    GOPATH : /home/upa/go2
    VSWCONF: /usr/local/etc/vsw.conf
  environment:
    GOPATH: "{{ GOPATH }}"
    PATH: "{{ lookup('env', 'PATH') }}:{{ GOPATH }}/bin"
    LD_LIBRARY_PATH: /usr/src/dpdk-stable-17.11.1/build/lib

  tasks:

  - name: spawn openconfid
    spawn:
      args: openconfigd -y modules:modules/policy:modules/bgp:modules/interfaces:modules/local-routing:modules/vlan:modules/rib:modules/network-instance:modules/types lagopus-router.yang
      cwd: "{{ GOPATH }}/src/github.com/lagopus/lagopus-router/yang"
      pidfile: /tmp/openconfid.pid
      stderr: /tmp/openconfigd-stderr
      stdout: /tmp/openconfigd-stdout
      respawn: true
    async: 10
    poll: 1

  - name: set hugepages
    hugepages: nr_pages=1024

  - name: bind device to dpdk driver
    devbind: device=000:01:00.0 driver=igb_uio

  - name: put vsw.conf
    copy: src=provisioning/vsw.conf dest={{ VSWCONF }}

  - name: spawn vsw
    spawn:
      args: vsw -v -f {{ VSWCONF }}
      pidfile: /tmp/vsw.pid
      stderr: /tmp/vsw-stderr
      stdout: /tmp/vsw-stdout
      respawn: true
    async: 10
    poll: 1
    become: yes

  - name: configure vsw
    vswconfig: config={{ item }}
    with_items:
      - set network-instances network-instance vsi3 config type L2VSI
      - set network-instances network-instance vsi3 config enabled true
      - commit
