
- hosts: yayoi2
  become: yes
  tasks:
  - name: install required packetgs
    apt: name={{ item }}
    with_items:
      - libnuma-dev
      - libelf-dev

  - name: set hugepages
    hugepages: nr_pages=1024

  - name: install dpdk
    dpdk_install: build_shared_lib=true jobs=6

  - name: dev bind to dpdk
    devbind: device=000:01:00.0 driver=igb_uio
