  
# ubuntu 18.04 does not have python2 by default
# but ansible still depends on python2
- hosts: lago1
  become: yes
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python

# configure lago1
- hosts: lago1
  vars:
    GOPATH : /home/vagrant/go
    VSWCONF: /home/vagrant/vsw.conf
  environment:
    GOPATH: "{{ GOPATH }}"
    PATH: "{{ lookup('env', 'PATH') }}:{{ GOPATH }}/bin"
    LD_LIBRARY_PATH: /usr/src/dpdk-stable-17.11.1/build/lib

  tasks:
  - include: setup.yml

  - name: configure vsw
    vswconfig: config={{ item }}
    with_items:
      - set network-instances network-instance vsi3 config type L2VSI
      - set network-instances network-instance vsi3 config enabled true
      - commit

